# Generated by Django 2.0.9 on 2018-11-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataentry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='pub_date',
            field=models.IntegerField(default=0, verbose_name='date published'),
        ),
    ]
